// Backs the "Pose Tool" dashboard page: given a reference photo (runway,
// lookbook, or any photo of a person in a pose), produces:
//   1. A structured, plain-English breakdown of the pose by body region,
//      written toward CLO3D's Avatar Pose editor — something a designer can
//      use to manually dial in the avatar's pose quickly instead of
//      eyeballing the photo joint-by-joint.
//   2. A 3-angle (front/side/back) turnaround of a neutral mannequin in that
//      same pose, generated by Gemini's image model, as a visual reference
//      sheet — NOT a real 3D mesh or skeleton (Gemini can't produce that; it
//      can only read an image and generate new ones), just a faster visual
//      reference than the single source photo.
//
// IMPORTANT HONESTY NOTE: any joint-angle language in the output is Gemini's
// visual *estimate*, not measured data. Treat it as a fast starting point for
// posing an avatar by hand, not as literal, precise rotation values.
const archiver = require("archiver");
const { nanoid } = require("nanoid");
const fs = require("fs");
const path = require("path");

// Same reasoning as lib/gemini.js: override via env if your account is on a
// different model. Vision (photo-in, JSON-out) reuses the text model since
// Gemini's flash models are natively multimodal; image generation needs its
// own image-capable model.
const GEMINI_MODEL = process.env.GEMINI_MODEL || "gemini-3.6-flash";
const GEMINI_IMAGE_MODEL = process.env.GEMINI_IMAGE_MODEL || "gemini-2.5-flash-image";
const GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta/models";

const POSE_SYSTEM_INSTRUCTION = `You are a fashion/fit specialist helping a CLO3D garment designer quickly pose a 3D avatar to match a reference photo.

Look at the photo of a person/model and describe their pose region by region, in plain language a designer can use to manually adjust CLO3D's Avatar Pose editor (which poses a skeleton with regions like head/neck, spine/torso, shoulders, arms, hands, hips, legs, feet). Where useful, give a rough qualitative angle (e.g. "left arm raised ~45° from torso, elbow bent ~90°") but always make clear these are visual estimates, not precise measurements.

Also write one single short, neutral, purely physical description of the body pose alone — no clothing, no face, no identity, no background — suitable as an image-generation prompt for a plain grey studio mannequin/dress-form in that exact pose. This description must be safe and generic: describe joint positions and stance only.

You MUST reply with ONLY a raw JSON object (no markdown fences, no commentary outside the JSON) in exactly this shape:
{
  "summary": "one or two sentence overview of the pose and its overall mood/energy",
  "stance": "footing/stance description, e.g. weight-bearing leg, foot placement",
  "weightDistribution": "short description of where the weight sits",
  "regions": {
    "headNeck": "...",
    "spineTorso": "...",
    "leftArm": "...",
    "rightArm": "...",
    "leftLeg": "...",
    "rightLeg": "..."
  },
  "clo3dTips": ["short actionable tip", "..."],
  "imagePrompt": "the neutral physical-pose-only description described above"
}`;

function safeParsePoseJson(raw) {
  if (!raw) return null;
  const cleaned = raw.trim().replace(/^```json\s*|^```\s*|```$/g, "").trim();
  try {
    const parsed = JSON.parse(cleaned);
    if (typeof parsed.imagePrompt !== "string") return null;
    return parsed;
  } catch {
    // Fall back to pulling out the first {...} block, in case the model
    // wrapped the JSON in stray commentary despite being told not to.
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");
    if (start === -1 || end === -1 || end <= start) return null;
    try {
      const parsed = JSON.parse(cleaned.slice(start, end + 1));
      if (typeof parsed.imagePrompt !== "string") return null;
      return parsed;
    } catch {
      return null;
    }
  }
}

/**
 * Sends the uploaded photo to Gemini and gets back a structured pose
 * breakdown plus a neutral image-generation prompt for the turnaround step.
 *
 * @param {Buffer} imageBuffer
 * @param {string} mimeType e.g. "image/png"
 * @returns {Promise<object>} parsed pose JSON (see POSE_SYSTEM_INSTRUCTION shape)
 */
async function analyzePose(imageBuffer, mimeType) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not configured on the server");
  }

  const contents = [
    {
      role: "user",
      parts: [
        { inline_data: { mime_type: mimeType, data: imageBuffer.toString("base64") } },
        { text: "Analyze the pose in this photo." },
      ],
    },
  ];

  const baseGenerationConfig = {
    maxOutputTokens: 3072,
    responseMimeType: "application/json",
  };

  async function callGemini(generationConfig) {
    const res = await fetch(`${GEMINI_API_BASE}/${GEMINI_MODEL}:generateContent?key=${apiKey}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        system_instruction: { parts: [{ text: POSE_SYSTEM_INSTRUCTION }] },
        contents,
        generationConfig,
      }),
    });
    return res;
  }

  // gemini-3.x flash models "think" before answering by default, billed out
  // of maxOutputTokens — worth disabling for a bounded structured-output
  // task like this one. But not every model build on this endpoint accepts
  // the thinkingConfig field (some 400 on it outright rather than just
  // rejecting a bad value), so this tries with it first and transparently
  // falls back to plain generationConfig if the model rejects the field,
  // rather than us having to hardcode which behavior applies.
  let res = await callGemini({ ...baseGenerationConfig, thinkingConfig: { thinkingBudget: 0 } });

  if (res.status === 400) {
    const retryText = await res.text().catch(() => "");
    console.error(
      "Pose analysis: model rejected thinkingConfig (%s), retrying without it: %s",
      res.status,
      retryText.slice(0, 300)
    );
    res = await callGemini(baseGenerationConfig);
  }

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error(`Gemini API error ${res.status}: ${errText.slice(0, 300)}`);
  }

  const data = await res.json();
  const candidate = data?.candidates?.[0];
  const raw = candidate?.content?.parts?.map((p) => p.text).join("") || "";
  const parsed = safeParsePoseJson(raw);

  if (!parsed) {
    // Log full diagnostics server-side — the route's central error handler
    // only sends the client a generic 500, so this is the only place we'll
    // see *why* it failed (truncation, a safety block, empty candidate, etc).
    console.error(
      "Pose analysis failed to parse. finishReason=%s promptFeedback=%o rawTextLength=%d rawTextPreview=%s",
      candidate?.finishReason,
      data?.promptFeedback,
      raw.length,
      raw.slice(0, 500)
    );

    if (candidate?.finishReason === "MAX_TOKENS") {
      throw new Error("Gemini ran out of output tokens while analyzing the pose. Please try again.");
    }
    if (candidate?.finishReason === "SAFETY" || data?.promptFeedback?.blockReason) {
      throw new Error("Gemini declined to analyze this photo. Please try a different one.");
    }
    throw new Error("Gemini returned an unexpected response while analyzing the pose.");
  }

  return parsed;
}

const ANGLE_PROMPTS = {
  front: "Front view (camera facing the figure directly), full body, head to toe visible.",
  side: "Side/profile view (camera at 90° to the figure), full body, head to toe visible.",
  back: "Back view (camera behind the figure), full body, head to toe visible.",
};

const IMAGE_STYLE_PREFIX =
  "A plain matte-grey featureless studio mannequin / dress-form figure (no face, no clothing, no hair, no skin tone, no identity), standing in the exact body pose described below, on a seamless white studio background, soft even lighting, orthographic-feeling full-body reference shot. ";

/**
 * Generates one turnaround-angle image via Gemini's image model.
 * Returns { buffer: Buffer|null, warning: string|null } — warning is set
 * whenever there's no image, explaining why, so callers/users don't just
 * see a silently empty slot.
 */
async function generateAngleImage(poseImagePrompt, angle) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not configured on the server");
  }

  const prompt = `${IMAGE_STYLE_PREFIX}${ANGLE_PROMPTS[angle]} Pose: ${poseImagePrompt}`;

  async function callGemini(generationConfig) {
    return fetch(`${GEMINI_API_BASE}/${GEMINI_IMAGE_MODEL}:generateContent?key=${apiKey}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig,
      }),
    });
  }

  // Some image-capable Gemini builds require BOTH modalities listed (image
  // models can also talk back in text), others reject the field outright.
  // Same adaptive-retry approach as analyzePose's thinkingConfig: try the
  // more-likely-correct shape first, fall back if the model 400s on it,
  // rather than assuming one fixed shape for a model we can't test live.
  let res = await callGemini({ responseModalities: ["TEXT", "IMAGE"] });

  if (res.status === 400) {
    const retryText = await res.text().catch(() => "");
    console.error(
      `Pose turnaround (${angle}): model rejected responseModalities (%s), retrying without it: %s`,
      res.status,
      retryText.slice(0, 300)
    );
    res = await callGemini(undefined);
  }

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error(`Gemini image API error ${res.status}: ${errText.slice(0, 300)}`);
  }

  const data = await res.json();
  const candidate = data?.candidates?.[0];
  const parts = candidate?.content?.parts || [];
  const imagePart = parts.find((p) => p.inlineData || p.inline_data);
  const inline = imagePart?.inlineData || imagePart?.inline_data;

  if (!inline?.data) {
    // No image came back — this is NOT thrown as an error (a missing angle
    // shouldn't fail the whole request), but it's logged with everything
    // needed to diagnose it, and surfaced as a warning the UI can show
    // instead of just leaving the slot blank with no explanation.
    const textParts = parts.map((p) => p.text).filter(Boolean).join(" ").trim();
    console.error(
      `Pose turnaround (${angle}): no image returned. finishReason=%s promptFeedback=%o textParts=%s`,
      candidate?.finishReason,
      data?.promptFeedback,
      textParts.slice(0, 300)
    );

    let warning = `The ${angle} view wasn't generated.`;
    if (candidate?.finishReason === "SAFETY" || data?.promptFeedback?.blockReason) {
      warning = `Gemini declined to generate the ${angle} view for this pose (safety filter).`;
    } else if (textParts) {
      warning = `Gemini didn't generate the ${angle} view: ${textParts.slice(0, 200)}`;
    }

    return { buffer: null, warning };
  }

  return { buffer: Buffer.from(inline.data, "base64"), warning: null };
}

/**
 * Generates all three turnaround angles. Best-effort per-angle: if one
 * angle fails, the others are still returned rather than failing the whole
 * request (mirrors the garment tool's "never fail the whole thing over an
 * optional extra" approach).
 *
 * @returns {Promise<{images: {front,side,back}, warnings: {front,side,back}}>}
 *   images values are Buffer|null, warnings values are string|null.
 */
async function generateTurnaroundImages(poseImagePrompt) {
  const angles = ["front", "side", "back"];
  const results = await Promise.all(
    angles.map(async (angle) => {
      try {
        const { buffer, warning } = await generateAngleImage(poseImagePrompt, angle);
        return [angle, { buffer, warning }];
      } catch (err) {
        console.error(`Pose turnaround (${angle}) generation failed:`, err.message);
        return [angle, { buffer: null, warning: `The ${angle} view failed to generate: ${err.message}` }];
      }
    })
  );

  const images = {};
  const warnings = {};
  for (const [angle, { buffer, warning }] of results) {
    images[angle] = buffer;
    warnings[angle] = warning;
  }
  return { images, warnings };
}

function poseNotesText(pose) {
  const lines = [
    "POSE REFERENCE NOTES (Gemini-generated visual estimate — treat angles as a starting point, not precise measurements)",
    "",
    `Summary: ${pose.summary || "-"}`,
    `Stance: ${pose.stance || "-"}`,
    `Weight distribution: ${pose.weightDistribution || "-"}`,
    "",
    "By region (for CLO3D's Avatar Pose editor):",
    `  Head / neck: ${pose.regions?.headNeck || "-"}`,
    `  Spine / torso: ${pose.regions?.spineTorso || "-"}`,
    `  Left arm: ${pose.regions?.leftArm || "-"}`,
    `  Right arm: ${pose.regions?.rightArm || "-"}`,
    `  Left leg: ${pose.regions?.leftLeg || "-"}`,
    `  Right leg: ${pose.regions?.rightLeg || "-"}`,
    "",
    "CLO3D tips:",
    ...(pose.clo3dTips || []).map((t) => `  - ${t}`),
  ];
  return lines.join("\n");
}

/**
 * Bundles the pose notes (JSON + readable text) and any generated
 * turnaround images into a single .zip, the same archiver-based pattern as
 * lib/garmentTool.js's buildGarmentZip.
 */
async function buildPoseZip({ pose, images }, destDir) {
  fs.mkdirSync(destDir, { recursive: true });
  const filename = `${nanoid(14)}-pose.zip`;
  const filePath = path.join(destDir, filename);

  await new Promise((resolve, reject) => {
    const output = fs.createWriteStream(filePath);
    const archive = archiver("zip", { zlib: { level: 9 } });

    output.on("close", resolve);
    archive.on("error", reject);
    archive.pipe(output);

    archive.append(JSON.stringify(pose, null, 2), { name: "pose-notes.json" });
    archive.append(poseNotesText(pose), { name: "pose-notes.txt" });

    for (const angle of ["front", "side", "back"]) {
      if (images[angle]) {
        archive.append(images[angle], { name: `reference/${angle}.png` });
      }
    }

    archive.finalize();
  });

  return filePath;
}

module.exports = {
  analyzePose,
  generateTurnaroundImages,
  buildPoseZip,
  poseNotesText,
};
