// POST /api/pose-tool/process (dashboard only, requires auth)
//
// Upload a reference photo, get back:
//   - structured pose notes (JSON + human-readable) written for CLO3D's
//     Avatar Pose editor
//   - a 3-angle (front/side/back) turnaround of a neutral mannequin in that
//     pose, generated by Gemini's image model — best-effort per angle
//   - the same bundled as a downloadable .zip (base64-encoded in the JSON
//     response, so the page can show an interactive preview AND offer a
//     one-click download from a single request)
//
// Every request makes up to 4 paid Gemini calls (1 vision + up to 3 image
// generations), so unlike the local-model garment tool, this is rate-limited
// per IP on top of requiring auth.
const express = require("express");
const fs = require("fs");
const os = require("os");
const path = require("path");

const { requireAuth } = require("../middleware/auth");
const { requirePremium } = require("../middleware/requirePremium");
const { poseUpload } = require("../middleware/poseUpload");
const { createRateLimiter } = require("../middleware/rateLimit");
const { analyzePose, generateTurnaroundImages, buildPoseZip } = require("../lib/poseTool");

const router = express.Router();

const poseRateLimit = createRateLimiter({
  windowMs: 60_000,
  max: 6,
  message: "The Pose Tool is getting a lot of use right now — please wait a moment and try again.",
});

router.post("/process", requireAuth, requirePremium, poseRateLimit, poseUpload.single("file"), async (req, res, next) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No file uploaded. Field name must be "file".' });
  }

  const cleanup = () => fs.unlink(req.file.path, () => {});

  try {
    const imageBuffer = await fs.promises.readFile(req.file.path);
    const mimeType = req.file.mimetype || "image/png";

    const pose = await analyzePose(imageBuffer, mimeType);
    const { images, warnings } = await generateTurnaroundImages(pose.imagePrompt);

    const zipDir = path.join(os.tmpdir(), "pose-tool-output");
    const zipPath = await buildPoseZip({ pose, images }, zipDir);
    const zipBase64 = (await fs.promises.readFile(zipPath)).toString("base64");
    fs.unlink(zipPath, () => {});

    const toDataUrl = (buf) => (buf ? `data:image/png;base64,${buf.toString("base64")}` : null);

    res.json({
      pose,
      images: {
        front: toDataUrl(images.front),
        side: toDataUrl(images.side),
        back: toDataUrl(images.back),
      },
      // Non-null whenever an angle didn't come back, explaining why —
      // so the UI can show a real reason instead of a silently empty slot.
      imageWarnings: warnings,
      zipBase64,
    });
  } catch (err) {
    if (err.message === "GEMINI_API_KEY is not configured on the server") {
      return res.status(503).json({ error: "The Pose Tool isn't configured yet — missing GEMINI_API_KEY." });
    }
    next(err);
  } finally {
    cleanup();
  }
});

module.exports = router;
